FROM alpine:3.20

# Instala o mínimo necessário para FTP **e** SSH
RUN apk add --no-cache \
    vsftpd \
    openssl \
    bash \
    openssh-server \
    openssh-keygen \
    supervisor

# Copia arquivo de configuração
COPY FTPS/vsftpd.conf /etc/vsftpd/vsftpd.conf
COPY FTPS/supervisord.conf /etc/supervisord.conf

# Copia entrypoint atualizado
COPY FTPS/entrypoint.sh /entrypoint.sh
RUN chmod +x /entrypoint.sh

# Cria diretórios exigidos pelo SSH
RUN mkdir -p /var/run/sshd

EXPOSE 20 21 50000-50003 22

CMD ["/entrypoint.sh"]
