services:
  bind9:
    image: ubuntu/bind9:edge
    container_name: bind9-container
    restart: unless-stopped
    env_file:
      - .env
    environment:
      - TZ=UTC
    volumes:
      - ./bind9_config:/etc/bind
    ports:
      - "${BIND9_PORT}:53/tcp"
      - "${BIND9_PORT}:53/udp"
    networks:
      internal-bind:
        ipv4_address: 10.0.0.2

  bind9slave:
    image: ubuntu/bind9:edge
    container_name: bind9slave-container
    restart: unless-stopped
    env_file:
      - .env
    environment:
      - TZ=UTC
    volumes:
      - ./bind9slave_config:/etc/bind
    ports:
      - "${BIND9SLAVE_PORT}:53/tcp"
      - "${BIND9SLAVE_PORT}:53/udp"
    networks:
      internal-bind:
        ipv4_address: 10.0.0.3

  nginx:
    image: nginx:mainline-alpine-perl
    container_name: nginx-container
    restart: unless-stopped
    env_file:
      - .env
    environment:
      DB_SQLITE_FILE: "/data/database.sqlite"
      IP_SERVIDOR: "${IP_SERVIDOR}"
      FTP_USER: "${FTP_USER}"
      FTP_PASS: "${FTP_PASS}"
    volumes:
      - ./nginx/data:/data
      - ./nginx/letsencrypt:/etc/letsencrypt
      - ./nginx/templates:/etc/nginx/templates
      - ./nginx/conf.d:/etc/nginx/conf.d
      - ./nginx/html:/etc/nginx/html
      - ./nginx/ssl:/etc/nginx/ssl
      - ./nginx/logs:/var/log/nginx
      - ./FTPS/setup_ftps.sh:/usr/local/bin/setup_ftps.sh:ro
    ports:
      - "${NGINX_HTTP}:80"
      - "${NGINX_HTTPS}:443"
      - "${NGINX_NOPR}:8080"
      - "${FTP_PORT}:21"
      - "${PASV_MIN}-${PASV_MAX}:40000-40100"
    networks:
      internal-bind:
        ipv4_address: 10.0.0.4
    command: >
      sh -c "
        apk add --no-cache bash vsftpd openssl lftp shadow &&
        chmod +x /usr/local/bin/setup_ftps.sh &&
        /usr/local/bin/setup_ftps.sh &&
        vsftpd /etc/vsftpd.conf &
        nginx -g 'daemon off;'
      "

networks:
  internal-bind:
    name: internal-bind
    driver: bridge
    ipam:
      config:
        - subnet: 10.0.0.0/24
          gateway: 10.0.0.1

