services:
  bind9:
    image: ubuntu/bind9:edge
    container_name: bind9-container
    restart: unless-stopped
    env_file:
      - .env
    environment:
      - TZ=UTC
    volumes:
      - ./bind9_config:/etc/bind
    ports:
      - "${BIND9_PORT}:53/tcp"
      - "${BIND9_PORT}:53/udp"
    networks:
      internal-bind:
        ipv4_address: 10.0.0.2

  bind9slave:
    image: ubuntu/bind9:edge
    container_name: bind9slave-container
    restart: unless-stopped
    env_file:
      - .env
    environment:
      - TZ=UTC
    volumes:
      - ./bind9slave_config:/etc/bind
    ports:
      - "${BIND9SLAVE_PORT}:53/tcp"
      - "${BIND9SLAVE_PORT}:53/udp"
    networks:
      internal-bind:
        ipv4_address: 10.0.0.3

  nginx:
    image: nginx:mainline-alpine-perl
    container_name: nginx-container
    restart: unless-stopped
    env_file:
      - .env
    environment:
      DB_SQLITE_FILE: "/data/database.sqlite"
    volumes:
      - ./nginx/data:/data
      - ./nginx/letsencrypt:/etc/letsencrypt
      - ./nginx/templates:/etc/nginx/templates
      - ./nginx/conf.d:/etc/nginx/conf.d
      - ./nginx/html:/etc/nginx/html
      - ./nginx/ssl:/etc/nginx/ssl
      - ./nginx/logs:/var/log/nginx
    ports:
      - "${NGINX_HTTP}:80"
      - "${NGINX_HTTPS}:443"
      - "${NGINX_NOPR}:8080"
    networks:
      internal-bind:
        ipv4_address: 10.0.0.4

  ftp:
    image: fauria/vsftpd
    container_name: ftp-container
    restart: unless-stopped
    env_file:
      - .env
    environment:
      FTP_USER: "${FTP_USER}" # root user
      FTP_PASS: "${FTP_PASS}"
      PASV_ADDRESS: "10.0.0.5"
      PASV_MIN_PORT: "${PASV_MIN}"
      PASV_MAX_PORT: "${PASV_MAX}"
      PASV_ENABLE: "YES"
      PASV_ADDR_RESOLVE: "NO"
      LOG_STDOUT: "YES"
    volumes:
      - ./FTPS/data:/home/vsftpd
      - ./FTPS/log:/var/log/vsftpd
    ports:
      - "${FTP_PORT}:21"
      - "${PASV_MIN}-${PASV_MAX}:${PASV_MIN}-${PASV_MAX}"
    networks:
      internal-bind:
        ipv4_address: 10.0.0.5

networks:
  internal-bind:
    name: internal-bind
    driver: bridge
    ipam:
      config:
        - subnet: 10.0.0.0/24
          gateway: 10.0.0.1

