server {
    listen 8080;
    server_name reports.angelcorp.com.br;
    root /etc/nginx/html/reports;
    index index.html index.htm;
    location / {
        try_files $uri $uri/ =404;
    }
    access_log /var/log/nginx/reports.angelcorp.com.br_access.log;
    error_log /var/log/nginx/reports.angelcorp.com.br_error.log;
}